version: "3"

services:
  api:
    container_name: 'ironbank-api'
    build:
      context: ./ironbank-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - 8081
    depends_on:
      - mysql
    # restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ironbank
      MYSQL_USER: ironhacker
      MYSQL_PASSWORD: 1r0nh4ck3r
    ports:
      - '3306:3306'
    expose:
      - 3306
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
